version: '3'

services:
  api:
    image: sails-cli:1.4.2
    command: sh -c "npm install && npm run debug"
    working_dir: /app
    ports:
      - '1337:1337'
      - '9229:9229'
    volumes: 
      - .:/app
    env_file:
      - ./sails.env
  db:
    container_name: mongodb
    image: mongo:4.4
    volumes:
      - ./mongo:/data/db
